# Numpy
* Usa arrays (parecido com vetores)

In [3]:
import numpy as np

vetor = np.zeros(5)
vetor

array([0., 0., 0., 0., 0.])

In [5]:
type(vetor)

numpy.ndarray

In [6]:
# Formato (shape)

vetor.shape

(5,)

In [8]:
# Mudando o shape

vetor.shape = (5,1)
vetor

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [9]:
# Criando vetores vazios

np.empty(5)

array([0., 0., 0., 0., 0.])

In [13]:
# Criando vetores com começo, fim e espaçamentos

np.linspace(0,1000,10)

array([   0.        ,  111.11111111,  222.22222222,  333.33333333,
        444.44444444,  555.55555556,  666.66666667,  777.77777778,
        888.88888889, 1000.        ])

In [14]:
# Operações com arrys

a = np.array([10,20,100,200,500])
b = np.array([3,4,5,6,7])

In [16]:
a + b

np.add(a, b)

array([ 13,  24, 105, 206, 507])

In [17]:
a - b

np.subtract(a, b)

array([  7,  16,  95, 194, 493])

In [18]:
a*b

np.multiply(a, b)

array([  30,   80,  500, 1200, 3500])

In [19]:
# Operações estatísticas

precos = np.array([22.14, 23.56, 23.89])

In [28]:
# Mínimo, Máximo, Mediana, Média, Desvio-padrão e Variância 

print(np.min(precos))
print(np.max(precos))
print(np.median(precos))
print(np.mean(precos))
print(np.std(precos))
print(np.var(precos))

22.14
23.89
23.56
23.19666666666667
0.7592247507966411
0.5764222222222217
